name: benchmark
channels:
  - conda-forge
  - bioconda
  - omnia
dependencies:
  - python=3.6
  - pandas  # TODO: add min. or exact versions!
  - snakemake
  - openmm
  - pymbar
  - openmoltools
  - mdtraj
  - parmed
  - packmol
  - jupyter
  - scikit-learn
  - lxml
  - networkx  # Needed because openforcefield is installed via pip
  - pip:
    - fire
    - arch
    - https://github.com/openforcefield/openforcefield/archive/0.0.3.zip
